### ISSUE TITLE
No modules named 'pytket' and 'jax'

### ISSUE THREAD

**Issue by pmeixler2** [oxford-quantum-group/discopy#10]
We completed the install of discopy and ran alice-loves-bob.ipynb.  When running cells 4 and 9, no modules named 'pytket' was rendered.  When running cells 14, 15, and 19, no modules named 'jax' was rendered.

pip install pytket
ERROR: Could not find a version that satisfies the requirement pytket (from versions: none)
ERROR: No matching distribution found for pytket

pip install --upgrade jax jaxlib
Collecting jax
  Downloading jax-0.1.68.tar.gz (345 kB)
     |████████████████████████████████| 345 kB 1.6 MB/s
ERROR: Could not find a version that satisfies the requirement jaxlib (from versions: none)
ERROR: No matching distribution found for jaxlib

Please assist,

**Comment by toumix** [comment]
Thanks for giving the notebook a try! It seems like I need to include more details on how to run it. The problem comes from pytket and jax not being requirements for DisCoPy, so you need to install them separately.

pytket and its dependencies are, however, included as requirements for testing, so you can try to run:
`pip install ".[test]"`
and you should get a working version.

I am unsure why you get "No matching distribution found for jaxlib" though. I found this issue: https://github.com/google/jax/issues/507 which suggests that the problem may come from the lack of jax support for Windows.

Note that you can ignore the cells running jax simulation and go straight to the quantum hardware instead (assuming you have pytket and IBMQ installed), for example running this notebook: https://github.com/oxford-quantum-group/discopy/blob/master/notebooks/qnlp-experiment.ipynb

**Comment by Subbu0894** [comment]
I am getting the following error. Please help me thanks
![t5](https://user-images.githubusercontent.com/66458131/83938892-d6d3a780-a81b-11ea-8ba7-38ba3a804498.JPG)

**Comment by toumix** [comment]
I've updated the requirements for the most recent version of pytket, this should be fixed now.
You just have to either `pip install discopy` then `pip install pytket` separately, or clone the repo locally then run `pip install ".[test]"`. I hope this helps.
