### ISSUE TITLE
Error installing discopy

### ISSUE THREAD

**Issue by herlimenezes** [oxford-quantum-group/discopy#11]
As I tried to install  discopy, using pip3 install discopý I got this error:
(NLP-project) [herlimenezes@localhost ~]$ pip3 install discopy
Collecting discopy
  Using cached https://files.pythonhosted.org/packages/09/8e/e6f47ca5b82f4c90675e63b57c5cb60b909473d8999114c1677f0cb3e6ba/discopy-0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pystp9a6/discopy/setup.py", line 16, in <module>
        TEST_REQ = [l.strip() for l in open('tests/requirements.txt').readlines()]
    FileNotFoundError: [Errno 2] No such file or directory: 'tests/requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-pystp9a6/discopy/

**Comment by toumix** [comment]
Thanks for raising the issue!
It looks like there is a problem of relative paths in the setup script. I will fix this ASAP and come back to you.
Meanwhile, you can still clone the repo and install directly from source:
```
git clone https://github.com/oxford-quantum-group/discopy.git
cd discopy
pip install .
```

**Comment by herlimenezes** [comment]
Thank you for your answer. Just another observation. Since Python 2.x is going to be deprecated, I have installed discopy using pip3 in a virtual environment.

**Comment by toumix** [comment]
After many trials and errors, I believe this should be fixed.
The problem came from the requirements file not being included in the package.
You can try to run `pip install discopy==0.2.5b3` and check it actually works.

As for your comment regarding Python 2.x, it is indeed soon-to-be deprecated and the DisCoPy package is intended for Python 3. I have added this metadata to the setup.py file to remove confusion.
