### ISSUE TITLE
Drawing doesn't work for complicated pregroup diagrams

### ISSUE THREAD

**Issue by y-richie-y** [oxford-quantum-group/discopy#12]
Take this diagram:
```python 
diagram = Diagram(dom=Ty(), cod=Ty('s'), boxes=[Word('Bruce', Ty('n')), Word('is', Ty(Ob('n', z=1), 's', Ob('n', z=-1))), Word('a', Ty('n', Ob('n', z=-1))), Word('beagle', Ty('n')), Cup(Ty(Ob('n', z=-1)), Ty('n')), Word('from', Ty(Ob('n', z=1), 'n', Ob('n', z=-1))), Word('Brazil', Ty('n')), Cup(Ty(Ob('n', z=-1)), Ty('n')), Cup(Ty('n'), Ty(Ob('n', z=1))), Cup(Ty(Ob('n', z=-1)), Ty('n')), Cup(Ty('n'), Ty(Ob('n', z=1)))], offsets=[0, 1, 4, 6, 5, 5, 8, 7, 4, 3, 0])
grammar.draw(diagram)
```
<img width="300" src="https://user-images.githubusercontent.com/13847804/96936182-7e94fd80-14bd-11eb-91c5-8c12f86dea53.png">

This cannot currently be drawn using `diagram.draw()`, which shows the diagram flattened with triangle states.
This is due to the way we currently do pregroup detection, which uses `diagram.foliation()` to check whether the first slice of the diagram contain only words as boxes and the rest of the slices contain only cups as boxes respectively.

**Comment by toumix** [comment]
The problem came from `grammar.draw` relying on `Diagram.normal_form` to make sure that the input had shape `word @ ... @ word >> cups`, which worked for simple cases but failed on complicated examples like this one.

I changed the method so that it will assume that the input already has the right shape, and output `ValueError` otherwise. 

![Screenshot 2020-10-23 at 14 28 17](https://user-images.githubusercontent.com/6673255/97007121-30294280-1541-11eb-9f47-1a04dfec2e8e.png)
