### ISSUE TITLE
Inconsistent gradients

### ISSUE THREAD

**Issue by aljabr0** [oxford-quantum-group/discopy#20]
Hi,  according to my calculations , I found an inconsistency while obtaining the gradient of a rotation gate, here the code:
```python
from sympy.abc import theta
from discopy.quantum import *

f = Ket(0) >> Rx(theta) >> Bra(1)
f = f >> f[::-1]

# We use the following definition for $R_x(\theta)$
# R_x(\theta) = \cos(\pi \theta) I - i \sin(\pi \theta) \sigma_x
#
# Now, we define a function f that represents our circuit:
# f(\theta) = \left|\bra{1} R_x(\theta) \ket{0} \right|^2 = \sin^2(\pi \theta)
# thus
# \pdv{f}{\theta} = \pi \sin(2\pi \theta)
#
# Some sample values:
# f(1/4) = \sin^2(\pi/4) = 1/2
# \left[\pdv{f}{\theta}\right](1/4) = \pi
#
# f(-1/4) = \sin^2(-\pi/4) = 1/2
# \left[\pdv{f}{\theta}\right](-1/4) = -\pi
#
# Also note that the function f is real whereas the gradient
# resulting from the code below is purely imaginary for the sample
# values indicated above.

p = -1/4    # Value used to eval f and df
print(f.subs(theta, p).eval()) # Here the result is as expected

print(f.grad(theta).subs(theta, p).eval())
```

The value corresponding to the second print (the one relative to grad) does not match my calculations, see above in the code the manual calculation of grad and the expected values. My results match the calculations of the library when I change in `gates.Rotation.grad(...)` the following line
```python
  def grad(self, var):
    # ...
    return scalar(-np.pi * gradient) @ type(self)(self.phase - .5)
```
Thanks

**Comment by aljabr0** [comment]
Update, my analysis above is centred on the single Qubit rotations, if it is the case that there's a bug, then I think the controlled rotations need review as well (e.g. CU1).

**Comment by y-richie-y** [comment]
Yup, good catch! 

The code was originally
`return scalar(.5j * gradient) @ type(self)(self.phase - .5)`

This came from differentiating the matrix exponential `exp(0.5j * theta * X)`. It turns out the imaginary part disappears when you convert the Pauli `X` in terms of a X rotation. Another problem was that I forgot that in DisCoPy  the rotation parameters are measured in 2pi turns.

![image](https://user-images.githubusercontent.com/13847804/103098695-b0a21780-4646-11eb-8bfe-952e172c6c77.png)

So I've changed it to

`return scalar(pi * gradient) @ type(self)(self.phase + .5)`

Currently differentiation for controlled rotations is disabled, so there is no bug there. If you want to differentiate controlled rotations, you can apply the zx functor `circuit2zx`, where `.grad()` works on *any* zx diagram!

![image](https://user-images.githubusercontent.com/13847804/103098258-18576300-4645-11eb-9760-5b1dda2742af.png)

**Comment by aljabr0** [comment]
Great, thanks!
